# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "php-roundtable"
client_id = "c01fa427fef81cdcca31ac25cb803455"
application_url = "https://vbulletin-jewelry-naval-driven.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://vbulletin-jewelry-naval-driven.trycloudflare.com/auth/callback",
  "https://vbulletin-jewelry-naval-driven.trycloudflare.com/auth/shopify/callback",
  "https://vbulletin-jewelry-naval-driven.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "seid-lp-s.myshopify.com"
